---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rc-mongo-uri
  namespace: uvasds-services
spec:
  encryptedData:
    MONGO_URI: AgCl1Q4w/lo37oAgvsWFjL6DZp/3hU0jSn0/KHAOjdwm+dXkMW0cHjVw7lsPuvIl5c7a94UFbZif9nMpDv0DGlCZXzI/V6PKfN0YzeTlpTbw18TSqJYVBQULwP8rpm8FVghpDwAtAbrXQ9wxuR6yG8vj2BIU9zdObNFJLKLpzlRV2DSwmm0UnwW/mxRVD+SAyC8iCg9cOe10/12gg3dKlYiPV5GC9em+2hlFdJzEFMSxQruPmuC063XEHAhfIwWIH4+pogevKV8QSvujMi49w5XQQToyqV5A7zcjbY+hFe9P/67ddL1Kb/eJfMZ1g4KcZIG1bgJ+HCI+FXHw0YXq1ewKOxcozLKepnxNKspuVvduEs4j+dA+EFVRE6Xj+7BW9mK5oaAvhX8Djl1oaP8JY0lqPGJVxu30KqmVCX9uFIUZkWzU/EwPYkqw+9yqsFtMOI76nQoDdh58U6/Z7041pC1nZEel9IKyVEHtTD9/4dXKouiQQk3y6VszTSti+lONCXOuCk2mt4dfCey8aJY3QzPAcwkXg1pOv8Q9kY8JDz+RzMb8KjLLTYeQ6h5hWr/3DYqp7i3UA4ThpdwDdwy4bw7omS5cN4SHRGCiKzqJPD/kacNhCqbAAGgk04DT/iHAEBAttwwH6SdtCzGkO9qIF0b2f0YxydKEDOFi3XtWsJfEIyBzoZ1OmUq2jJZm2h9ns9c5YNbw7VfDy+qM95SK0HFHKN3DG5djLXLth4K2YXIqYPRuLk92ZYZ3zISUGDKrR1Qy5DyFwAWL/eLCCVx16krjZkmBatGHleGFHLPmPnjVo12AcXcMUZ/jdaV/5l0COVB4j9NdVaLPl4EYLVLjcw1K1vQx+h9jWqYb
  template:
    metadata:
      name: rc-mongo-uri
      namespace: uvasds-services
    type: Opaque
