apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot-deployment
  namespace: uvasds-services
  labels:
    app: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
      - name: discord-bot-container
        image: ghcr.io/nmagee/discord-bot:1.0
        imagePullPolicy: Always
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-token
              key: DISCORD_TOKEN
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-nem2p-440848399208
              key: AWS_ACCESS_KEY_ID
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-nem2p-440848399208
              key: AWS_DEFAULT_REGION
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-nem2p-440848399208
              key: AWS_SECRET_ACCESS_KEY
        resources:
          requests:
            memory: "524Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
